#!/usr/bin/env sh
gsettings set org.gnome.desktop.wm.preferences disable-workarounds "false"
gsettings set org.gnome.desktop.wm.preferences focus-new-windows "'smart'"
gsettings set org.gnome.desktop.wm.preferences action-right-click-titlebar "'menu'"
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "'<Super>'"
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar "'lower'"
gsettings set org.gnome.desktop.wm.preferences titlebar-uses-system-font "false"
gsettings set org.gnome.desktop.wm.preferences theme "'Ambiance'"
gsettings set org.gnome.desktop.wm.preferences num-workspaces "6"
gsettings set org.gnome.desktop.wm.preferences raise-on-click "true"
gsettings set org.gnome.desktop.wm.preferences auto-raise "false"
gsettings set org.gnome.desktop.wm.preferences visual-bell "false"
gsettings set org.gnome.desktop.wm.preferences focus-mode "'click'"
gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar "'toggle-maximize'"
gsettings set org.gnome.desktop.wm.preferences auto-raise-delay "500"
gsettings set org.gnome.desktop.wm.preferences button-layout "'close,minimize,maximize:'"
gsettings set org.gnome.desktop.wm.preferences workspace-names "['']"
gsettings set org.gnome.desktop.wm.preferences audible-bell "true"
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button "false"
gsettings set org.gnome.desktop.wm.preferences titlebar-font "'Ubuntu Bold 11'"
gsettings set org.gnome.desktop.wm.preferences visual-bell-type "'fullscreen-flash'"