#!/usr/bin/env sh
gsettings set org.compiz.integrated run-command-3 "['Disabled']"
gsettings set org.compiz.integrated display-all-workspaces "true"
gsettings set org.compiz.integrated run-command-4 "['Disabled']"
gsettings set org.compiz.integrated show-hud "['<Alt>F1']"
gsettings set org.compiz.integrated run-command-8 "['Disabled']"
gsettings set org.compiz.integrated run-command-9 "['Disabled']"
gsettings set org.compiz.integrated run-command-12 "['Disabled']"
gsettings set org.compiz.integrated run-command-1 "['<Super>v']"
gsettings set org.compiz.integrated run-command-10 "['Disabled']"
gsettings set org.compiz.integrated command-10 "''"
gsettings set org.compiz.integrated command-11 "''"
gsettings set org.compiz.integrated command-3 "''"
gsettings set org.compiz.integrated command-4 "''"
gsettings set org.compiz.integrated command-21 "'/usr/bin/gnome-system-monitor -p'"
gsettings set org.compiz.integrated command-12 "''"
gsettings set org.compiz.integrated command-1 "'bash -ic gvim'"
gsettings set org.compiz.integrated command-2 "''"
gsettings set org.compiz.integrated command-6 "''"
gsettings set org.compiz.integrated command-7 "''"
gsettings set org.compiz.integrated command-5 "''"
gsettings set org.compiz.integrated command-9 "''"
gsettings set org.compiz.integrated run-command-21 "['<Control><Alt>Delete']"
gsettings set org.compiz.integrated command-8 "''"
gsettings set org.compiz.integrated command-screenshot "'gnome-screenshot'"
gsettings set org.compiz.integrated run-command-11 "['Disabled']"
gsettings set org.compiz.integrated command-window-screenshot "'gnome-screenshot -w'"
gsettings set org.compiz.integrated run-command-5 "['Disabled']"
gsettings set org.compiz.integrated run-command-6 "['Disabled']"
gsettings set org.compiz.integrated run-command-7 "['Disabled']"
gsettings set org.compiz.integrated run-command-2 "['Disabled']"