#!/usr/bin/env sh
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "['<Shift><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings minimize "['<Primary><Alt>KP_0']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left "['<Super><Shift>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-11 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-12 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-center "['']"
gsettings set org.gnome.desktop.wm.keybindings unmaximize "['<Primary><Super>Down', '<Super>Down', '<Alt>F5']"
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['<Super>s', '<Alt>F1']"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['<Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings cycle-panels-backward "['<Shift><Control><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['<Alt>F2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>Down']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-ne "['<Primary><Alt>KP_Prior']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-e "['<Primary><Alt>KP_Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Alt><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings always-on-top "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Alt><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings raise "['']"
gsettings set org.gnome.desktop.wm.keybindings maximize "['<Primary><Super>Up', '<Super>Up', '<Primary><Alt>KP_5']"
gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward "['<Shift><Alt>F6']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-n "['<Primary><Alt>KP_Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-s "['<Primary><Alt>KP_Down']"
gsettings set org.gnome.desktop.wm.keybindings maximize-horizontally "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-side-w "['<Primary><Alt>KP_Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-nw "['<Primary><Alt>KP_Home']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['']"
gsettings set org.gnome.desktop.wm.keybindings begin-move "['<Alt>F7']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down "['<Super><Shift>Down']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Alt><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-se "['<Primary><Alt>KP_Next']"
gsettings set org.gnome.desktop.wm.keybindings activate-window-menu "['<Alt>space']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Super>space']"
gsettings set org.gnome.desktop.wm.keybindings toggle-above "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right "['<Super><Shift>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift><Super>space']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last "['<Super><Shift>End']"
gsettings set org.gnome.desktop.wm.keybindings lower "['']"
gsettings set org.gnome.desktop.wm.keybindings cycle-panels "['<Control><Alt>Escape']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['']"
gsettings set org.gnome.desktop.wm.keybindings toggle-on-all-workspaces "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up "['<Super><Shift>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-corner-sw "['<Primary><Alt>KP_End']"
gsettings set org.gnome.desktop.wm.keybindings toggle-shaded "['<Primary><Alt>s']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>Home']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['']"
gsettings set org.gnome.desktop.wm.keybindings raise-or-lower "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-panels "['<Control><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-panels-backward "['<Shift><Control><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab', '<Shift><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings maximize-vertically "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['']"
gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Primary><Super>d', '<Primary><Alt>d', '<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab', '<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-11 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-12 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super>a']"
gsettings set org.gnome.desktop.wm.keybindings set-spew-mark "['']"
gsettings set org.gnome.desktop.wm.keybindings begin-resize "['<Alt>F8']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Alt><Super>Down']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last "['<Super>End']"
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group "['<Super>Above_Tab', '<Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings cycle-group "['<Alt>F6']"
gsettings set org.gnome.desktop.wm.keybindings close "['<Super>q']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Super><Shift>Home']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']"