#!/usr/bin/env bash
if exists-container 'portainer' ; then
  docker start portainer
else
  docker run --name=portainer -d -p 9080:9000 -v "/var/run/docker.sock:/var/run/docker.sock" portainer/portainer
fi
echo 'portainer run at localhost:9080'
