#!/usr/bin/env bash
if exists-container 'portainer' ; then
  docker start portainer
else
  docker volume create portainer_data
  docker run --name=portainer -d \
    -p 127.0.0.1:9080:9000 \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -v portainer_data:/data portainer/portainer-ce
fi
echo 'portainer run at http://127.0.0.1:9080'
