#!/usr/bin/env bash

echo 'test'
. "$MYSCRIPTS_HOME/common.sh"

source-myscript "commands/index.sh"
source-myscript "alias.sh"
source-myscript "boot.sh"
source-myscript "myscripts.sh"
# source-myscript "keyboard.sh"
